ARG APP_VERSION="latest"

FROM grafana/promtail:${APP_VERSION}
USER root

ARG APP_VERSION
LABEL org.opencontainers.image.version="${APP_VERSION}"


ARG CACHEBUST=1

# INSERT_HARDENING_HERE

USER promtail
