FROM cryptpad/cryptpad:latest

USER root

# Alpine Linux 用の最新パッケージの適用とキャッシュの完全パージ
RUN apk update && \
    apk upgrade --no-cache && \
    rm -rf /var/cache/apk/*

RUN rm -f /bin/su /usr/bin/sudo || true

USER 4001
